export interface PortfolioItem {
  slug: string;
  title: string;
  tagline: string;
  overview: string;
  deliverables: string[];
  techStack: string[];
  results: string[];
  clientCount: number;
  clientIndustries: string[];
  icon: string;
  gradient: string;
  category: string;
  heroImage: string;
  architectureImage: string;
  heroBlurDataURL: string;
  architectureBlurDataURL: string;
}

export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
  slug: "ad-analytics-reporting",
  title: "Automated Ad Analytics & Reporting",
  tagline: "15+ hours of weekly reporting - eliminated.",
  overview:
  "Automated ad analytics and reporting systems for agencies managing campaigns across Google Ads and Facebook Ads. These systems pull live performance data, calculate attribution across the full funnel, and deliver polished weekly 7-day reports - all without a single manual export.",
  deliverables: [
  "Automated weekly 7-day performance reports across Google Ads and Facebook Ads",
  "Real-time conversion attribution pipeline connecting ad clicks to downstream revenue",
  "Multi-platform data aggregation into unified Google Sheets dashboards",
  "Funnel conversion tracking from impression through to closed deal",
  "Branded, client-ready report generation in Google Docs",
  "Scheduled data pulls with error handling and alerting",
  ],
  techStack: ["n8n", "Make.com", "Google Ads API", "Facebook Ads API", "Google Sheets", "Google Docs"],
  results: [
  "15+ hours per week of manual reporting eliminated",
  "Real-time conversion attribution replacing delayed manual tracking",
  "Automated weekly client reports delivered on schedule",
  "Zero missed weeks or formatting errors",
  ],
  clientCount: 6,
  clientIndustries: ["Digital Advertising", "E-commerce", "Performance Marketing"],
  icon: "chart",
  gradient: "from-blue-500 to-cyan-500",
  category: "Analytics & Reporting",
  heroImage: "/images/portfolio/ad-analytics-reporting.png",
  architectureImage: "/images/blog/ad-analytics-reporting.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAME/8QAGRABAQEAAwAAAAAAAAAAAAAAAQADEiFR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABURAQEAAAAAAAAAAAAAAAAAAABB/9oADAMBAAIRAxEAPwDBmBocgTymnbJODX//2Q==",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAGRABAAIDAAAAAAAAAAAAAAAAAAECESEx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDOwk13PAUH/9k=",
  },
  {
  slug: "creative-strategy-copywriting",
  title: "AI-Powered Creative Strategy & Copywriting",
  tagline: "From blank page to launch-ready copy in minutes.",
  overview:
  "AI-powered creative strategy and copywriting systems that generate ad copy, landing page content, and marketing collateral at scale. From chiropractic ad creation to knowledge base generation, these workflows produce launch-ready content calibrated to client brand voice and audience.",
  deliverables: [
  "AI-generated ad copy and creative briefs for Facebook and Google campaigns",
  "Automated knowledge base generation from client intake data",
  "Landing page copywriting workflows with brand-voice calibration",
  "FAQ generation and content mapping for service businesses",
  "Multi-variant copy testing frameworks",
  ],
  techStack: ["OpenAI GPT", "n8n", "Make.com", "Google Docs", "Airtable"],
  results: [
  "Copy production time reduced from days to minutes",
  "Consistent brand voice maintained across all assets",
  "Multi-variant creative testing at scale",
  "Knowledge bases generated automatically from intake forms",
  ],
  clientCount: 5,
  clientIndustries: ["Healthcare Marketing", "Wellness", "Medical Practices"],
  icon: "pen",
  gradient: "from-purple-500 to-pink-500",
  category: "Content & Creative",
  heroImage: "/images/portfolio/creative-strategy-copywriting.png",
  architectureImage: "/images/blog/creative-strategy-copywriting.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAHRAAAgIBBQAAAAAAAAAAAAAAAQIAEQMSISIxUf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFhEAAwAAAAAAAAAAAAAAAAAAAAEx/9oADAMBAAIRAxEAPwDDipWtgDtKYpqPEd+REooB0//Z",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAGBABAAMBAAAAAAAAAAAAAAAAAAECESH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8Az8Sa9Ahf/9k=",
  },
  {
  slug: "ai-video-production",
  title: "Fully Automated AI Video Production",
  tagline: "15 YouTube channels. Zero manual editing.",
  overview:
  "A fully automated video production pipeline managing 15 YouTube channels simultaneously - from story generation through scripting, image creation, AI video generation, audio production, compilation, and upload. 90+ interconnected n8n workflows coordinate the entire process.",
  deliverables: [
  "End-to-end automated video production pipeline from concept to YouTube upload",
  "AI-driven story generation and script writing for diverse channel themes",
  "Automated image creation and AI video generation using Google Veo 3.1",
  "Audio production and synchronization integrated into the pipeline",
  "FFmpeg-based video compilation and rendering automation",
  "Direct YouTube upload with metadata, thumbnails, and scheduling",
  ],
  techStack: ["n8n", "Google Veo 3.1", "OpenAI GPT", "YouTube API", "FFmpeg"],
  results: [
  "90+ automated workflows orchestrating complete video lifecycle",
  "Dozens of videos produced daily across the channel network",
  "15 YouTube channels managed with zero manual intervention",
  "Production turnaround reduced from days to hours",
  ],
  clientCount: 3,
  clientIndustries: ["Media & Entertainment", "Digital Publishing"],
  icon: "video",
  gradient: "from-red-500 to-orange-500",
  category: "AI Video & Media",
  heroImage: "/images/portfolio/ai-video-production.png",
  architectureImage: "/images/blog/ai-video-production.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAaEAEAAgMBAAAAAAAAAAAAAAABAAIDESJB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAQADAAAAAAAAAAAAAAAAAAABMUH/2gAMAwEAAhEDEQA/AIcIFugTUWv06PYiOKDX/9k=",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAGRABAAIDAAAAAAAAAAAAAAAAAAECESEx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDPwk13yAUH/9k=",
  },
  {
  slug: "client-onboarding-automation",
  title: "Zero-Touch Client Onboarding",
  tagline: "Contract to kickoff in under 90 seconds.",
  overview:
  "Automated client onboarding systems that handle every step from contract signing through project setup. Invoice generation, Slack channel creation, project board provisioning, welcome email dispatch, and CRM updates - all triggered automatically.",
  deliverables: [
  "Automated trigger-based onboarding sequences from contract signature",
  "Invoice generation and payment tracking integration",
  "Slack workspace and channel provisioning for new clients",
  "Project management board creation with templated task lists",
  "Welcome email sequences with resource delivery",
  "CRM record creation and pipeline stage updates",
  ],
  techStack: ["n8n", "Make.com", "Zapier", "GoHighLevel", "Slack", "Airtable"],
  results: [
  "6+ hours saved per client onboarding",
  "Sub-90-second execution from trigger to completion",
  "Zero manual handoffs between systems",
  "100% consistency across all new client setups",
  ],
  clientCount: 4,
  clientIndustries: ["Agency Coaching", "SaaS", "Startup Incubation"],
  icon: "rocket",
  gradient: "from-green-500 to-emerald-500",
  category: "Business Operations",
  heroImage: "/images/portfolio/client-onboarding-automation.png",
  architectureImage: "/images/blog/client-onboarding-automation.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAZEAADAQEBAAAAAAAAAAAAAAAAARECIQP/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8Ag85nV0rwNKviAGL/2Q==",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAGhAAAgIDAAAAAAAAAAAAAAAAAAECIRExgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AzcWuEcbegCg//9k=",
  },
  {
  slug: "crm-appointment-setting",
  title: "AI-Powered CRM & Appointment Setting",
  tagline: "24/7 AI booking. Zero missed calls.",
  overview:
  "AI-powered appointment booking and CRM automation using Vapi voice AI for natural phone conversations, automated call quality scoring, and GoHighLevel workflow automation for reminders and review requests. These systems keep the pipeline full without manual intervention.",
  deliverables: [
  "24/7 AI-powered appointment booking via Vapi voice AI phone agents",
  "Automated call quality scoring and performance grading",
  "GoHighLevel CRM workflow automation for confirmations and follow-ups",
  "Post-appointment automated review request sequences",
  "No-show recovery workflows with automated re-engagement",
  ],
  techStack: ["n8n", "Make.com", "Vapi AI", "GoHighLevel", "Google Sheets"],
  results: [
  "24/7 AI appointment setting without staffing costs",
  "Automated call grading for consistent quality scoring",
  "Integrated CRM workflows eliminating manual follow-ups",
  "Reduced no-show rates through automated sequences",
  ],
  clientCount: 5,
  clientIndustries: ["Performance Marketing", "Healthcare", "Real Estate"],
  icon: "phone",
  gradient: "from-cyan-500 to-blue-500",
  category: "Voice AI & CRM",
  heroImage: "/images/portfolio/crm-appointment-setting.png",
  architectureImage: "/images/blog/crm-appointment-setting.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAME/8QAGhABAQACAwAAAAAAAAAAAAAAAQADEQIhof/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDDiNZeC6aaCvXskhf/2Q==",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAFxABAAMAAAAAAAAAAAAAAAAAAAESYf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AzkrkAoP/2Q==",
  },
  {
  slug: "social-media-content-automation",
  title: "Social Media Content Automation",
  tagline: "One input. 40 posts. Zero headcount added.",
  overview:
  "End-to-end social media content automation pipelines that transform single inputs into multi-platform content. Automated posting, scheduling, analytics collection, and performance reporting across all major social platforms.",
  deliverables: [
  "Multi-platform content generation from single input sources",
  "Automated scheduling and posting across social channels",
  "Social media analytics aggregation and reporting",
  "AI-powered caption and hashtag generation",
  "Content calendar automation with approval workflows",
  ],
  techStack: ["n8n", "Make.com", "OpenAI GPT", "Airtable", "Buffer", "Google Sheets"],
  results: [
  "10x content output without additional headcount",
  "Consistent posting schedules across all platforms",
  "Automated performance tracking and reporting",
  "Brand voice consistency maintained at scale",
  ],
  clientCount: 4,
  clientIndustries: ["Creator Economy", "Digital Marketing", "E-commerce"],
  icon: "share",
  gradient: "from-pink-500 to-purple-500",
  category: "Content & Creative",
  heroImage: "/images/portfolio/social-media-content-automation.png",
  architectureImage: "/images/blog/social-media-content-automation.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEE/8QAGxAAAwACAwAAAAAAAAAAAAAAAAECESEDEkH/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABcRAQADAAAAAAAAAAAAAAAAAAABMUH/2gAMAwEAAhEDEQA/AMPEpms0s6LSns9egFIoNf/Z",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAGRABAAIDAAAAAAAAAAAAAAAAAAECESEx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDPwk13yAUH/9k=",
  },
  {
  slug: "lead-gen-email-marketing",
  title: "Lead Generation & Email Marketing Automation",
  tagline: "Leads captured. Nurtured. Converted. Automatically.",
  overview:
  "Automated lead generation and email/SMS nurture systems that capture, qualify, and convert leads without manual intervention. From opt-in to conversion, every touchpoint is automated with personalized sequences.",
  deliverables: [
  "Automated lead capture from multiple channels into unified CRM",
  "AI-powered lead scoring and qualification workflows",
  "Multi-step email and SMS nurture sequences",
  "Behavioral trigger-based follow-up automation",
  "Conversion tracking and attribution reporting",
  ],
  techStack: ["n8n", "GoHighLevel", "ActiveCampaign", "Zapier", "Airtable"],
  results: [
  "40% increase in lead-to-customer conversion rates",
  "Automated nurture sequences reducing manual follow-up by 70%",
  "Real-time lead scoring enabling faster sales prioritization",
  "Multi-channel attribution tracking across email and SMS",
  ],
  clientCount: 7,
  clientIndustries: ["B2B Lead Generation", "SaaS", "Agency Services"],
  icon: "mail",
  gradient: "from-amber-500 to-red-500",
  category: "Lead Generation",
  heroImage: "/images/portfolio/lead-gen-email-marketing.png",
  architectureImage: "/images/blog/lead-gen-email-marketing.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAZEAADAQEBAAAAAAAAAAAAAAAAARECAxL/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFREBAQAAAAAAAAAAAAAAAAAAAAH/2gAMAwEAAhEDEQA/AIeXnOrpVQOVxADgV//Z",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAZEAEAAgMAAAAAAAAAAAAAAAAAARECITH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AJ1WTjvkAoP/2Q==",
  },
  {
  slug: "ecommerce-shopify-analytics",
  title: "E-commerce & Shopify Analytics Automation",
  tagline: "Real-time store intelligence. Zero spreadsheets.",
  overview:
  "Automated e-commerce analytics and inventory tracking systems for Shopify stores. Real-time sales dashboards, automated inventory alerts, and performance reporting that replace manual spreadsheet tracking.",
  deliverables: [
  "Automated Shopify sales and revenue dashboards",
  "Real-time inventory tracking with restock alerts",
  "Customer behavior analytics and segmentation",
  "Automated order fulfillment status reporting",
  "Multi-store aggregation for portfolio-level insights",
  ],
  techStack: ["n8n", "Shopify API", "Google Sheets", "Airtable", "Slack"],
  results: [
  "Real-time sales visibility replacing manual reporting",
  "Automated inventory alerts preventing stockouts",
  "Customer segmentation enabling targeted marketing",
  "Multi-store data unified in single dashboard",
  ],
  clientCount: 3,
  clientIndustries: ["Franchise Operations", "E-commerce", "Retail"],
  icon: "cart",
  gradient: "from-green-400 to-teal-500",
  category: "E-commerce",
  heroImage: "/images/portfolio/ecommerce-shopify-analytics.png",
  architectureImage: "/images/blog/ecommerce-shopify-analytics.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAGhAAAgMBAQAAAAAAAAAAAAAAAQIAERIDof/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAWEQADAAAAAAAAAAAAAAAAAAAAATH/2gAMAwEAAhEDEQA/AMXHKuC6gipJzo0vsRGoB0//2Q==",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIF/8QAGRABAAIDAAAAAAAAAAAAAAAAAAECESEx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDPwma75AKD/9k=",
  },
  {
  slug: "chatbot-automation",
  title: "AI Chatbot Development & Automation",
  tagline: "Instant responses. Infinite patience. 24/7 coverage.",
  overview:
  "AI-powered chatbot systems built on Botpress, ManyChat, and Voiceflow for customer support, lead qualification, and appointment booking. These bots handle complex conversation flows with natural language understanding.",
  deliverables: [
  "Custom AI chatbots for website, Facebook Messenger, and WhatsApp",
  "Lead qualification conversation flows with CRM integration",
  "Customer support automation with knowledge base retrieval",
  "Appointment booking bots with calendar integration",
  "Multi-language support and sentiment detection",
  ],
  techStack: ["Botpress", "ManyChat", "Voiceflow", "OpenAI GPT", "n8n", "GoHighLevel"],
  results: [
  "50% reduction in response times for customer inquiries",
  "24/7 lead qualification without human agents",
  "Automated appointment booking improving conversion by 35%",
  "Customer satisfaction scores maintained above 90%",
  ],
  clientCount: 4,
  clientIndustries: ["Healthcare", "Recruitment", "Professional Services"],
  icon: "bot",
  gradient: "from-indigo-500 to-purple-600",
  category: "Conversational AI",
  heroImage: "/images/portfolio/chatbot-automation.png",
  architectureImage: "/images/blog/chatbot-automation.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAGRABAAMBAQAAAAAAAAAAAAAAAQACERIh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAVEQEBAAAAAAAAAAAAAAAAAAAAQf/aAAwDAQACEQMRAD8AwV5LHVdMkOK+ERKQX//Z",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAXEAEAAwAAAAAAAAAAAAAAAAAAERJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAVEQEBAAAAAAAAAAAAAAAAAAAAAf/aAAwDAQACEQMRAD8AnQVwFCv/2Q==",
  },
  {
  slug: "billing-invoice-automation",
  title: "Billing & Invoice Automation",
  tagline: "Invoices sent. Payments tracked. Errors eliminated.",
  overview:
  "Automated billing, invoicing, and payment tracking systems that eliminate manual financial admin. From invoice generation to payment reconciliation, every step runs on autopilot with error handling and alerting.",
  deliverables: [
  "Automated invoice generation triggered by project milestones",
  "Payment tracking and reconciliation workflows",
  "Overdue payment reminder sequences",
  "Revenue reporting and financial dashboards",
  "Integration with Chargebee and payment processors",
  ],
  techStack: ["n8n", "Chargebee", "Google Sheets", "Airtable", "Slack"],
  results: [
  "Invoice generation time reduced from hours to seconds",
  "Zero manual payment tracking - fully automated reconciliation",
  "Overdue payments reduced through automated reminder sequences",
  "Real-time revenue visibility across all accounts",
  ],
  clientCount: 3,
  clientIndustries: ["SaaS", "Financial Services", "Logistics"],
  icon: "invoice",
  gradient: "from-emerald-500 to-green-600",
  category: "Business Operations",
  heroImage: "/images/portfolio/billing-invoice-automation.png",
  architectureImage: "/images/blog/billing-invoice-automation.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEE/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACERJRYf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFREBAQAAAAAAAAAAAAAAAAAAAEH/2gAMAwEAAhEDEQA/AMEuZfaVXBKy6byvQCgx/9k=",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAGhAAAgIDAAAAAAAAAAAAAAAAAAECIRExQf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8Az8VwjjekAUH/2Q==",
  },
  {
  slug: "market-research-competitor-analysis",
  title: "AI Market Research & Competitor Analysis",
  tagline: "Intel your competitors wish they had. Automated.",
  overview:
  "AI-powered market research and competitor analysis systems that continuously monitor competitive landscapes, aggregate industry data, and deliver actionable intelligence reports - replacing manual research with automated pipelines.",
  deliverables: [
  "Automated competitor monitoring and alerting systems",
  "AI-powered market trend analysis and reporting",
  "Competitive pricing and positioning intelligence",
  "Industry benchmark data aggregation",
  "Scheduled intelligence reports delivered to stakeholders",
  ],
  techStack: ["n8n", "OpenAI GPT", "Google Sheets", "Airtable", "Web Scraping APIs"],
  results: [
  "Research time reduced from days to hours",
  "Continuous competitor monitoring replacing periodic manual checks",
  "AI-generated insights identifying market opportunities",
  "Automated reporting keeping stakeholders informed in real-time",
  ],
  clientCount: 5,
  clientIndustries: ["Staffing & HR", "Marketing", "Consulting"],
  icon: "search",
  gradient: "from-violet-500 to-indigo-600",
  category: "Analytics & Reporting",
  heroImage: "/images/portfolio/market-research-competitor-analysis.png",
  architectureImage: "/images/blog/market-research-competitor-analysis.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEE/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACERIiIf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFREBAQAAAAAAAAAAAAAAAAAAAEH/2gAMAwEAAhEDEQA/AMFNavVR8kQy8kRKQX//2Q==",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAGhABAAEFAAAAAAAAAAAAAAAAAAECESFBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AzbcSac6BQf/Z",
  },
  {
  slug: "website-funnel-building",
  title: "Website & Funnel Building Automation",
  tagline: "From design to deploy. Zero bottlenecks.",
  overview:
  "Automated website and funnel building systems that streamline the entire creation process. Template provisioning, content population, and deployment workflows that reduce launch times from weeks to days.",
  deliverables: [
  "Automated funnel template provisioning and customization",
  "Content population workflows from intake forms",
  "GoHighLevel funnel and website automation",
  "A/B testing infrastructure with automated traffic splitting",
  "Performance tracking and conversion optimization",
  ],
  techStack: ["GoHighLevel", "ClickFunnels", "Webflow", "n8n", "Make.com"],
  results: [
  "Funnel launch time reduced from weeks to days",
  "Template-based provisioning ensuring brand consistency",
  "Automated A/B testing improving conversion rates by 25%",
  "275+ members supported with automated infrastructure",
  ],
  clientCount: 4,
  clientIndustries: ["Agency Coaching", "SaaS", "Startup Incubation"],
  icon: "globe",
  gradient: "from-blue-600 to-cyan-500",
  category: "Web & Funnels",
  heroImage: "/images/portfolio/website-funnel-building.png",
  architectureImage: "/images/blog/website-funnel-building.png",
  heroBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAGhAAAwEAAwAAAAAAAAAAAAAAAAECERIhIv/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AwxxT9TvRNqXdNLNYBQX/2Q==",
  architectureBlurDataURL: "data:image/jpeg;base64,/9j/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAGAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAGBABAQADAAAAAAAAAAAAAAAAAAEREmH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AM3FTW8BQf/Z",
  },
];

export const PORTFOLIO_CATEGORIES = [
  ...new Set(PORTFOLIO_ITEMS.map((item) => item.category)),
];
