const fs = require('fs');

const script = [
  'const { google } = require("googleapis");',
  'const fs = require("fs");',
  'const readline = require("readline");',
  'const { exec } = require("child_process");',
  '',
  'const keyFilePath = "C:/Users/ahmad/Downloads/ahmad-bukhari-website-b0a7f02305ae.json";',
  'const keyFile = JSON.parse(fs.readFileSync(keyFilePath, "utf8"));',
  'const SERVICE_EMAIL = keyFile.client_email;',
  '',
  'function ask(question) {',
  '  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });',
  '  return new Promise(resolve => rl.question(question, answer => { rl.close(); resolve(answer.trim()); }));',
  '}',
  '',
  'function openBrowser(url) {',
  '  const cmd = process.platform === "win32" ? "start" : process.platform === "darwin" ? "open" : "xdg-open";',
  '  exec(cmd + " " + url);',
  '}',
  '',
  'async function main() {',
  '  console.log("=== Ahmad Bukhari Portfolio - Leads Spreadsheet Creator ===");',
  '  console.log("");',
  '  console.log("IMPORTANT: Service accounts on consumer Google accounts cannot create files.");',
  '  console.log("We will create the spreadsheet in YOUR Google Drive, then configure it.");',
  '  console.log("");',
  '  console.log("Step 1: Opening Google Sheets in your browser...");',
  '  console.log("  -> A new blank spreadsheet will open.");',
  '  console.log("  -> Share it with: " + SERVICE_EMAIL);',
  '  console.log("  -> Give it Editor access.");',
  '  console.log("  -> Then copy the spreadsheet URL from your browser.");',
  '  console.log("");',
  '',
  '  openBrowser("https://sheets.new");',
  '  console.log("");',
  '',
  '  const rawInput = await ask("Paste the spreadsheet URL or ID here: ");',
  '',
  '  // Extract spreadsheet ID from URL or use as-is',
  '  let spreadsheetId = rawInput;',
  '  const match = rawInput.match(/\/spreadsheets\/d\/([a-zA-Z0-9_-]+)/);',
  '  if (match) spreadsheetId = match[1];',
  '',
  '  console.log("");',
  '  console.log("Using Spreadsheet ID:", spreadsheetId);',
  '',
  '  // Authenticate with service account',
  '  const auth = new google.auth.GoogleAuth({',
  '    credentials: { client_email: keyFile.client_email, private_key: keyFile.private_key },',
  '    scopes: ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"],',
  '  });',
  '',
  '  const authClient = await auth.getClient();',
  '  const sheets = google.sheets({ version: "v4", auth: authClient });',
  '  const drive = google.drive({ version: "v3", auth: authClient });',
  '',
  '  // Step 2: Rename spreadsheet and sheet tab',
  '  console.log("Step 2: Configuring spreadsheet...");',
  '  const spreadsheet = await sheets.spreadsheets.get({ spreadsheetId });',
  '  const sheetId = spreadsheet.data.sheets[0].properties.sheetId;',
  '',
  '  // Rename title and sheet tab',
  '  const requests = [];',
  '',
  '  // Rename spreadsheet title',
  '  requests.push({',
  '    updateSpreadsheetProperties: {',
  '      properties: { title: "Ahmad Bukhari Portfolio - Leads" },',
  '      fields: "title",',
  '    },',
  '  });',
  '',
  '  // Rename sheet tab to Leads',
  '  requests.push({',
  '    updateSheetProperties: {',
  '      properties: { sheetId: sheetId, title: "Leads" },',
  '      fields: "title",',
  '    },',
  '  });',
  '',
  '  await sheets.spreadsheets.batchUpdate({ spreadsheetId, requestBody: { requests } });',
  '  console.log("  Renamed spreadsheet and sheet tab.");',
  '',
  '  // Step 3: Add header row',
  '  const headers = [',
  '    "Timestamp", "Name", "Email", "Phone", "Company",',
  '    "Service Interest", "Budget Range", "Message", "Source",',
  '    "Country", "City", "Region", "User Agent", "Referer",',
  '  ];',
  '',
  '  console.log("Step 3: Adding header row...");',
  '  await sheets.spreadsheets.values.update({',
  '    spreadsheetId,',
  '    range: "Leads!A1:N1",',
  '    valueInputOption: "RAW",',
  '    requestBody: { values: [headers] },',
  '  });',
  '',
  '  // Step 4: Format header row (bold, background, freeze)',
  '  console.log("Step 4: Formatting header row (bold + frozen)...");',
  '  await sheets.spreadsheets.batchUpdate({',
  '    spreadsheetId,',
  '    requestBody: {',
  '      requests: [',
  '        {',
  '          repeatCell: {',
  '            range: {',
  '              sheetId: sheetId,',
  '              startRowIndex: 0,',
  '              endRowIndex: 1,',
  '              startColumnIndex: 0,',
  '              endColumnIndex: 14,',
  '            },',
  '            cell: {',
  '              userEnteredFormat: {',
  '                textFormat: { bold: true },',
  '                backgroundColor: { red: 0.9, green: 0.9, blue: 0.9 },',
  '              },',
  '            },',
  '            fields: "userEnteredFormat(textFormat,backgroundColor)",',
  '          },',
  '        },',
  '        {',
  '          updateSheetProperties: {',
  '            properties: {',
  '              sheetId: sheetId,',
  '              gridProperties: { frozenRowCount: 1 },',
  '            },',
  '            fields: "gridProperties.frozenRowCount",',
  '          },',
  '        },',
  '      ],',
  '    },',
  '  });',
  '',
  '  // Step 5: Verify sharing - the user already shared it with the service account',
  '  // Make sure ahmadbukhari4245@gmail.com has editor access too',
  '  console.log("Step 5: Verifying sharing...");',
  '  const perms = await drive.permissions.list({ fileId: spreadsheetId, fields: "permissions(emailAddress,role)" });',
  '  const hasUser = perms.data.permissions.some(p => p.emailAddress === "ahmadbukhari4245@gmail.com");',
  '  if (hasUser) {',
  '    console.log("  ahmadbukhari4245@gmail.com already has access.");',
  '  } else {',
  '    await drive.permissions.create({',
  '      fileId: spreadsheetId,',
  '      requestBody: { type: "user", role: "writer", emailAddress: "ahmadbukhari4245@gmail.com" },',
  '      sendNotificationEmail: true,',
  '    });',
  '    console.log("  Shared with ahmadbukhari4245@gmail.com as editor.");',
  '  }',
  '',
  '  const spreadsheetUrl = "https://docs.google.com/spreadsheets/d/" + spreadsheetId;',
  '',
  '  console.log("");',
  '  console.log("========================================");',
  '  console.log("SUCCESS! Spreadsheet configured.");',
  '  console.log("========================================");',
  '  console.log("Spreadsheet ID:", spreadsheetId);',
  '  console.log("Spreadsheet URL:", spreadsheetUrl);',
  '  console.log("Shared with: ahmadbukhari4245@gmail.com (editor)");',
  '  console.log("Sheet tab: Leads");',
  '  console.log("Headers:", headers.join(", "));',
  '}',
  
